#ifndef __16BITCOLORS_H
#define __16BITCOLORS_H

#define COLOR_WHITE 0xFFFF
#define COLOR_BLACK 0x0

#define COLOR_GREEN 0x07F0
#define COLOR_BLUE 0x001F
#define COLOR_RED 0xF800

#define COLOR_YELLOW 0xFFE0
#define COLOR_CYAN 0x07FF
#define COLOR_MAGENTA 0xF81F

#endif