name: 📖 Build Docs
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: "Doxygen Documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt install doxygen
          sudo apt install graphviz
          cd code/rafting-button/doc
          doxygen Doxyfile
          
